name: Build
on:
  pull_request:
    branches:
      - kr
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Download Dalamud Latest
        run: |
          Invoke-WebRequest -Uri https://raw.githubusercontent.com/dal4kr/Dalamud.Resources/main/Dalamud/Release/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip -DestinationPath "$env:AppData\XIVLauncherKR\addon\Hooks\dev"

      - name: Restore NuGet Packages
        run: dotnet restore     BossMod/BossModReborn.csproj

      - name: Build Plugin
        run: dotnet build --no-restore -c Release BossMod/BossModReborn.csproj